= Installation

include::home::overview.adoc[tag=rust-rewrite]

== TypeDB

Installation guides for the server-side database management software.

[cols-1]
--
.xref:guides::installation/cloud.adoc[TypeDB Cloud (DBaaS)]
[.clickable]
****
Fully-featured managed cloud offering.
Deploy TypeDB Cloud with a cloud platform designed by Vaticle specifically for TypeDB.
****

.xref:guides::installation/cloud-self-deployment.adoc[Self-deployed TypeDB Cloud (on premise)]
[.clickable]
****
Host and manage your own TypeDB Cloud deployment in a Kubernetes cluster.
****

.xref:guides::installation/core.adoc[TypeDB Core]
[.clickable]
****
Install TypeDB Core -- open-source edition of TypeDB.
****
--

== TypeDB clients

Installation guides for the client-side software able to connect to TypeDB.

[cols-1]
--
.xref:guides::installation/studio.adoc[Studio]
[.clickable]
****
Install an IDE that facilitates the development process for TypeDB databases.
****

.xref:guides::installation/console.adoc[Console]
[.clickable]
****
Install a powerful CLI tool able to work in interactive(REPL) and non-interactive (script) modes.
****

.xref:guides::installation/drivers.adoc[Drivers]
[.clickable]
****
Install libraries that implement TypeDB protocol and provide native driver API for programmatic access to TypeDB.
****
--
