= Database management with Drivers
:tabs-sync-option:

This guide covers database management operations, like creating, listing, and deleting databases with Drivers.
Make sure to xref:guides::installation/drivers.adoc[install]
and try to xref:guides::connection/drivers.adoc[connect] a chosen TypeDB driver to TypeDB before proceeding.

== Create

Use the following example to create a database:

[tabs]
====
Rust::
+
--
[,rust]
----
let databases = DatabaseManager::new(driver);
databases.create("db1");
----
--

Python::
+
--
[,python]
----
driver.databases().create("db1")
----
--

Java::
+
--
[,java]
----
driver.databases().create("db1");
----
--

Node.js::
+
--
[,js]
----
await driver.databases().create("db1");
----
--

C++::
+
--
[,cpp]
----
driver.databases.create("db1");
----
--
====

== Delete

Use the following example to delete a database:

.Managing databases
[tabs]
====
Rust::
+
--
[,rust]
----
let databases = DatabaseManager::new(driver);
databases.get("db1").unwrap().delete();
----
--

Python::
+
--
[,python]
----
driver.databases().get("db1").delete()
----
--

Java::
+
--
[,java]
----
driver.databases().get("db1").delete();
----
--

Node.js::
+
--
[,js]
----
await (await driver.databases().get("db1")).delete();
----
--

C++::
+
--
[,cpp]
----
driver.databases.get("db1").deleteDatabase();
----
--
====

== List

Use the following example to list all databases:

.Managing databases
[tabs]
====
Rust::
+
--
[,rust]
----
for db in databases.all().unwrap(){
    println!("{}", db.name().to_string());
}
----
--

Python::
+
--
[,python]
----
for db in driver.databases.all():
    print(db.name)
----
--

Java::
+
--
[,java]
----
driver.databases().all().forEach(db -> System.out.println(db.name()));
----
--

Node.js::
+
--
[,js]
----
let dbs = await driver.databases.all();
for (db of dbs) {
    console.log(db.name);
}
----
--

C++::
+
--
[,cpp]
----
for (auto& db: driver.databases.all()) {
    std::cout << db.name() << std::endl;
}
----
//std::vector<TypeDB::Database> databases;
//for (auto& database: driver.databases.all()) {
//     std::cout << database.name() << std::endl;
//}

--
====

== Check if exists

Use the following example to check the existence of a database:

[tabs]
====
Rust::
+
--
[,rust]
----
databases.contains("db1").unwrap();
----
--

Python::
+
--
[,python]
----
driver.databases().contains("db1")
----
--

Java::
+
--
[,java]
----
driver.databases().contains("db1");
----
--

Node.js::
+
--
[,js]
----
await driver.databases().contains("db1");
----
--

C++::
+
--
[,js]
----
driver.databases.contains("db1");
----
--
====
